name: pytorch
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - backcall=0.2.0=py_0
  - blas=1.0=mkl
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=pyhd3eb1b0_3
  - cudatoolkit=10.1.243=h6bb024c_0
  - cycler=0.10.0=py36_0
  - dbus=1.13.18=hb2f20db_0
  - decorator=4.4.2=py_0
  - expat=2.2.10=he6710b0_2
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.2=h5ab3b9f_0
  - glib=2.66.1=h92f7085_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - icu=58.2=he6710b0_3
  - intel-openmp=2020.2=254
  - ipython=7.16.1=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py36_0
  - jedi=0.17.2=py36_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.2.0=py36hfd86e86_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=he19cac6_1
  - lz4-c=1.9.2=he6710b0_1
  - matplotlib=3.3.1=0
  - matplotlib-base=3.3.1=py36h817c723_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.2.0=py36h23d657b_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - networkx=2.5=py_0
  - ninja=1.10.1=py36hfd86e86_0
  - olefile=0.46=py36_0
  - openssl=1.1.1h=h7b6447c_0
  - pandas=1.1.3=py36he6710b0_0
  - parso=0.7.0=py_0
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=7.2.0=py36hb39fc2d_0
  - pip=20.2.3=py36_0
  - prompt-toolkit=3.0.8=py_0
  - ptyprocess=0.6.0=py36_0
  - pygments=2.7.1=py_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py36h05f1152_2
  - python=3.6.12=hcff3b4d_2
  - python-dateutil=2.8.1=py_0
  - pytorch=1.6.0=py3.6_cuda10.1.243_cudnn7.6.3_0
  - pytz=2020.1=py_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - setuptools=50.3.0=py36_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.15.0=py_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - torchvision=0.7.0=py36_cu101
  - tornado=6.0.4=py36h7b6447c_1
  - traitlets=4.3.3=py36_0
  - wcwidth=0.2.5=py_0
  - wheel=0.35.1=py_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - absl-py==0.11.0
    - astunparse==1.6.3
    - attrs==20.3.0
    - blis==0.4.1
    - cached-property==1.5.2
    - cachetools==4.1.1
    - catalogue==1.0.0
    - chardet==3.0.4
    - click==7.1.2
    - cymem==2.0.4
    - dataclasses==0.7
    - en-core-web-sm==2.3.1
    - filelock==3.0.12
    - future==0.18.2
    - gast==0.3.3
    - google-auth==1.23.0
    - google-auth-oauthlib==0.4.2
    - google-pasta==0.2.0
    - grpcio==1.33.2
    - h5py==2.10.0
    - idna==2.10
    - importlib-metadata==2.0.0
    - joblib==0.17.0
    - keras==2.2.0
    - keras-applications==1.0.2
    - keras-preprocessing==1.1.2
    - markdown==3.3.3
    - murmurhash==1.0.4
    - nltk==3.5
    - numpy==1.18.5
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - packaging==20.4
    - plac==1.1.3
    - preshed==3.0.4
    - protobuf==3.13.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyyaml==5.3.1
    - regex==2020.11.11
    - requests==2.25.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - sacremoses==0.0.43
    - scikit-learn==0.23.2
    - scipy==1.4.1
    - sentencepiece==0.1.91
    - sklearn==0.0
    - snap-stanford==5.0.0
    - spacy==2.3.2
    - srsly==1.0.4
    - tensorboard==2.4.0
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.3.1
    - tensorflow-estimator==2.3.0
    - termcolor==1.1.0
    - thinc==7.4.1
    - threadpoolctl==2.1.0
    - tokenizers==0.9.3
    - torchtext==0.7.0
    - tqdm==4.51.0
    - transformers==3.5.0
    - urllib3==1.26.1
    - wasabi==0.8.0
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - zipp==3.4.0
prefix: /home/xinshuai/anaconda3/envs/pytorch

